### ISSUE TITLE
이벤트핸들러 교체를 지원해야합니다.

### ISSUE THREAD

**Issue by skt-t1-byungi** [nhn/toast-ui.react-editor#6]
## Version
current (19/04/22)

## Test Environment
sorry, no test 😜 

## Current Behavior
```jsx
<Editor onFocus={condition ? onFocus1 : onFocus2} />
```
condition이 반전됐을때 이벤트핸들러가 교체되지않습니다.

## Expected Behavior
hook이 도입전엔 condition을 이벤트 핸들러안에 넣는것이 바른 practice였으나,
hook이 들어오면서 condition을 포함한 내부 컨텍스트가 바뀌었을때 이벤트핸들러 역시 교체됩니다.
```jsx
const onFocus = useCallback(()=>{ /*...*/}, [condition])
<Editor onFocus={onFocus} />
```
업데이트마다 레퍼런스를 체크해 핸들러를 교체해야합니다

**Comment by jung-han** [comment]
v1.0.1에 포함될 예정입니다. 문의 감사합니다. 🙏

**Comment by jung-han** [comment]
@skt-t1-byungi v1.0.1에 포함되었습니다. 이슈 감사합니다.
